version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    minor-versions:
      applies-to: version-updates
      update-types: 
      - minor
      - patch
  assignees:
  - "nu12"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - "nu12"